### ISSUE TITLE
HtHead can be broken.

### ISSUE THREAD

**Issue by VsSekorin** [yegor256/cactoos-http#42] opened 2018-05-04 06:28 UTC
Now `HtHead` reads block, then checks it. Therefore, the situation is possible:
`... \r\n` - block 1
`\r\n ...` - block 2
In this case, `HtHead#stream` does not find `\r\n\r\n`.

**Comment by 0crat** [comment] 2018-05-04 06:28
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by llorllale** [comment] 2018-05-15 14:32
@0crat in

**Comment by 0crat** [comment] 2018-05-15 14:34
> @0crat in ([here](https://github.com/yegor256/cactoos-http/issues/42#issuecomment-389188903))

@llorllale Job [#42](https://github.com/yegor256/cactoos-http/issues/42) is now in scope, role is `DEV`

**Comment by 0crat** [comment] 2018-05-16 15:46
The job [#42](https://github.com/yegor256/cactoos-http/issues/42) assigned to @sharpler[/z](https://www.0crat.com/u/sharpler), here is [why](https://www.0crat.com/footprint/C63314D6Z/1361552499); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by SharplEr** [comment] 2018-05-26 15:40
@0crat waiting
Waiting for reviewer for #56

**Comment by 0crat** [comment] 2018-05-26 15:41
> @0crat waiting Waiting for reviewer for #56  ([here](https://github.com/yegor256/cactoos-http/issues/42#issuecomment-392269235))

@SharplEr The impediment for [#42](https://github.com/yegor256/cactoos-http/issues/42) was registered successfully by @sharpler[/z](https://www.0crat.com/u/sharpler)

**Comment by 0crat** [comment] 2018-07-18 18:33
> @0crat refuse ([here](https://github.com/yegor256/cactoos-http/issues/42#issuecomment-406030988))

@SharplEr The user @sharpler[/z](https://www.0crat.com/u/sharpler) resigned from [#42](https://github.com/yegor256/cactoos-http/issues/42), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment] 2018-07-18 18:33
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @sharpler[/z](https://www.0crat.com/u/sharpler)

**Comment by 0crat** [comment] 2019-01-03 16:46
The job [#42](https://github.com/yegor256/cactoos-http/issues/42) assigned to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), here is [why](https://www.0crat.com/footprint/C63314D6Z/40add5b9-dbe0-4b98-bc3b-fc33e45157ae); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by ammaratef45** [comment] 2019-01-03 18:14
@llorllale where is the design documentation for this? I can't figure it out without seeing the design

**Comment by llorllale** [comment] 2019-01-03 21:07
@ammaratef45 do you have specific questions?

**Comment by ammaratef45** [comment] 2019-01-03 21:10
The issue isn't clear for me,
What is the block and how can a block being terminated in the block after it

**Comment by llorllale** [comment] 2019-01-04 13:17
@ammaratef45 the issue refers to the way `HtHead` reads the stream in "blocks" or chunks while parsing it, looking for the `\r\n\r\n` delimiter

**Comment by 0crat** [comment] 2019-01-13 18:46
The job [#42](https://github.com/yegor256/cactoos-http/issues/42) assigned to @ilyakharlamov[/z](https://www.0crat.com/u/ilyakharlamov), here is [why](https://www.0crat.com/footprint/C63314D6Z/95b1cf0e-5b45-4dc5-9fda-a93728f56b1f); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by ilyakharlamov** [comment] 2019-02-26 01:31
@0crat status

**Comment by 0crat** [comment] 2019-02-26 01:32
> @0crat status ([here](https://github.com/yegor256/cactoos-http/issues/42#issuecomment-467255464))

@ilyakharlamov This is what I know about this job in [C63314D6Z](https://www.0crat.com/p/C63314D6Z), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#42](https://github.com/yegor256/cactoos-http/issues/42) is [in scope](http://www.zerocracy.com/policy.html#14) for 10mon
  * The role is `DEV`
  * The job is assigned to @ilyakharlamov[/z](https://www.0crat.com/u/ilyakharlamov) for [1mon](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @vssekorin[/z](https://www.0crat.com/u/vssekorin): This user reported the ticket
    * @sharpler[/z](https://www.0crat.com/u/sharpler): User was resigned from the ticket
    * @ammaratef45[/z](https://www.0crat.com/u/ammaratef45): User was resigned from the ticket
  * Job [footprint](https://www.0crat.com/footprint/C63314D6Z?q=%7Bjob%3A%27gh%3Ayegor256%2Fcactoos-http%2342%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by ilyakharlamov** [comment] 2019-03-17 02:24
@llorllale ping, the PR was merged a while ago

**Comment by llorllale** [comment] 2019-03-17 13:49
@ilyakharlamov ask the ticket's reporter if we can close this

**Comment by ilyakharlamov** [comment] 2019-03-18 20:10
@VsSekorin ping

**Comment by ilyakharlamov** [comment] 2019-04-16 15:09
@VsSekorin the PR was merged, I believe you can close this ticket.

**Comment by 0crat** [comment] 2019-06-01 15:58
The job [#42](https://github.com/yegor256/cactoos-http/issues/42) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/C63314D6Z/28271511-bc62-4c62-b5bb-bd1641c4901a); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by victornoel** [comment] 2019-06-01 15:59
@VsSekorin @llorllale someone can close this? the PR has been merged

**Comment by victornoel** [comment] 2019-06-01 16:00
@0crat waiting for issue to be closed

**Comment by 0crat** [comment] 2019-06-01 16:00
> @0crat waiting for issue to be closed ([here](https://github.com/yegor256/cactoos-http/issues/42#issuecomment-497956305))

@victornoel The impediment for [#42](https://github.com/yegor256/cactoos-http/issues/42) was registered successfully by @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by victornoel** [comment] 2019-06-03 17:48
@VsSekorin @llorllale ping

**Comment by llorllale** [comment] 2019-06-07 01:47
@VsSekorin closed due to inactivity (PR #69 merged for this)

**Closed by llorllale** 2019-06-07 01:47 UTC
Labels: bug, scope, waiting

**Comment by 0crat** [comment] 2019-06-07 02:13
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @victornoel[/z](https://www.0crat.com/u/victornoel), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment] 2019-06-07 02:15
The job [#42](https://github.com/yegor256/cactoos-http/issues/42) is now out of scope

**Comment by sereshqua** [comment] 2019-06-07 11:19
@victornoel she we wait until [issue](https://github.com/zerocracy/farm/issues/2070) has been review or already give `quality bad` here?

**Comment by victornoel** [comment] 2019-06-07 12:02
@sereshqua no, it's not needed, it is independent, thanks for checking :)

**Comment by sereshqua** [comment] 2019-06-07 19:32
@0crat quality bad

**Comment by 0crat** [comment] 2019-06-07 19:33
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment] 2019-06-07 19:59
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)

**Comment by g4s8** [comment] 2019-09-16 09:23
@0crat status

**Comment by 0crat** [comment] 2019-09-16 09:29
> @0crat status ([here](https://github.com/yegor256/cactoos-http/issues/42#issuecomment-531701603))

@g4s8 This is what I know about this job in [C63314D6Z](https://www.0crat.com/p/C63314D6Z), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#42](https://github.com/yegor256/cactoos-http/issues/42) is not in scope
  * Job [footprint](https://www.0crat.com/footprint/C63314D6Z?q=%7Bjob%3A%27gh%3Ayegor256%2Fcactoos-http%2342%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)
